# Generated by Django 6.0.5 on 2026-05-10 16:08

import randomtext.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120, validators=[randomtext.models.validate_short_text])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
