# Generated by Django 6.0.5 on 2026-05-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randomtext', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shorttext',
            table='shorttext',
        ),
    ]
